from typing import Any

from google.longrunning.operations_proto_pb2 import *

class OperationsStub:
    GetOperation: Any = ...
    ListOperations: Any = ...
    CancelOperation: Any = ...
    DeleteOperation: Any = ...
    def __init__(self, channel: Any) -> None: ...
