# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from google.protobuf.struct_pb2 import Struct as google___protobuf___struct_pb2___Struct
from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)
from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class AttributeContext(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Peer(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class LabelsEntry(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            key: typing___Text = ...
            value: typing___Text = ...
            def __init__(
                self,
                *,
                key: typing___Optional[typing___Text] = None,
                value: typing___Optional[typing___Text] = None,
            ) -> None: ...
            def ClearField(
                self,
                field_name: typing_extensions___Literal[
                    "key", b"key", "value", b"value"
                ],
            ) -> None: ...
        type___LabelsEntry = LabelsEntry

        ip: typing___Text = ...
        port: builtin___int = ...
        principal: typing___Text = ...
        region_code: typing___Text = ...
        @property
        def labels(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...
        def __init__(
            self,
            *,
            ip: typing___Optional[typing___Text] = None,
            port: typing___Optional[builtin___int] = None,
            labels: typing___Optional[
                typing___Mapping[typing___Text, typing___Text]
            ] = None,
            principal: typing___Optional[typing___Text] = None,
            region_code: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "ip",
                b"ip",
                "labels",
                b"labels",
                "port",
                b"port",
                "principal",
                b"principal",
                "region_code",
                b"region_code",
            ],
        ) -> None: ...
    type___Peer = Peer
    class Api(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        service: typing___Text = ...
        operation: typing___Text = ...
        protocol: typing___Text = ...
        version: typing___Text = ...
        def __init__(
            self,
            *,
            service: typing___Optional[typing___Text] = None,
            operation: typing___Optional[typing___Text] = None,
            protocol: typing___Optional[typing___Text] = None,
            version: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "operation",
                b"operation",
                "protocol",
                b"protocol",
                "service",
                b"service",
                "version",
                b"version",
            ],
        ) -> None: ...
    type___Api = Api
    class Auth(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        principal: typing___Text = ...
        audiences: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
            typing___Text
        ] = ...
        presenter: typing___Text = ...
        access_levels: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
            typing___Text
        ] = ...
        @property
        def claims(self) -> google___protobuf___struct_pb2___Struct: ...
        def __init__(
            self,
            *,
            principal: typing___Optional[typing___Text] = None,
            audiences: typing___Optional[typing___Iterable[typing___Text]] = None,
            presenter: typing___Optional[typing___Text] = None,
            claims: typing___Optional[google___protobuf___struct_pb2___Struct] = None,
            access_levels: typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions___Literal["claims", b"claims"]
        ) -> builtin___bool: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "access_levels",
                b"access_levels",
                "audiences",
                b"audiences",
                "claims",
                b"claims",
                "presenter",
                b"presenter",
                "principal",
                b"principal",
            ],
        ) -> None: ...
    type___Auth = Auth
    class Request(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class HeadersEntry(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            key: typing___Text = ...
            value: typing___Text = ...
            def __init__(
                self,
                *,
                key: typing___Optional[typing___Text] = None,
                value: typing___Optional[typing___Text] = None,
            ) -> None: ...
            def ClearField(
                self,
                field_name: typing_extensions___Literal[
                    "key", b"key", "value", b"value"
                ],
            ) -> None: ...
        type___HeadersEntry = HeadersEntry

        id: typing___Text = ...
        method: typing___Text = ...
        path: typing___Text = ...
        host: typing___Text = ...
        scheme: typing___Text = ...
        query: typing___Text = ...
        size: builtin___int = ...
        protocol: typing___Text = ...
        reason: typing___Text = ...
        @property
        def headers(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...
        @property
        def time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...
        @property
        def auth(self) -> type___AttributeContext.Auth: ...
        def __init__(
            self,
            *,
            id: typing___Optional[typing___Text] = None,
            method: typing___Optional[typing___Text] = None,
            headers: typing___Optional[
                typing___Mapping[typing___Text, typing___Text]
            ] = None,
            path: typing___Optional[typing___Text] = None,
            host: typing___Optional[typing___Text] = None,
            scheme: typing___Optional[typing___Text] = None,
            query: typing___Optional[typing___Text] = None,
            time: typing___Optional[
                google___protobuf___timestamp_pb2___Timestamp
            ] = None,
            size: typing___Optional[builtin___int] = None,
            protocol: typing___Optional[typing___Text] = None,
            reason: typing___Optional[typing___Text] = None,
            auth: typing___Optional[type___AttributeContext.Auth] = None,
        ) -> None: ...
        def HasField(
            self,
            field_name: typing_extensions___Literal["auth", b"auth", "time", b"time"],
        ) -> builtin___bool: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "auth",
                b"auth",
                "headers",
                b"headers",
                "host",
                b"host",
                "id",
                b"id",
                "method",
                b"method",
                "path",
                b"path",
                "protocol",
                b"protocol",
                "query",
                b"query",
                "reason",
                b"reason",
                "scheme",
                b"scheme",
                "size",
                b"size",
                "time",
                b"time",
            ],
        ) -> None: ...
    type___Request = Request
    class Response(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class HeadersEntry(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            key: typing___Text = ...
            value: typing___Text = ...
            def __init__(
                self,
                *,
                key: typing___Optional[typing___Text] = None,
                value: typing___Optional[typing___Text] = None,
            ) -> None: ...
            def ClearField(
                self,
                field_name: typing_extensions___Literal[
                    "key", b"key", "value", b"value"
                ],
            ) -> None: ...
        type___HeadersEntry = HeadersEntry

        code: builtin___int = ...
        size: builtin___int = ...
        @property
        def headers(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...
        @property
        def time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...
        def __init__(
            self,
            *,
            code: typing___Optional[builtin___int] = None,
            size: typing___Optional[builtin___int] = None,
            headers: typing___Optional[
                typing___Mapping[typing___Text, typing___Text]
            ] = None,
            time: typing___Optional[
                google___protobuf___timestamp_pb2___Timestamp
            ] = None,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions___Literal["time", b"time"]
        ) -> builtin___bool: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "code", b"code", "headers", b"headers", "size", b"size", "time", b"time"
            ],
        ) -> None: ...
    type___Response = Response
    class Resource(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class LabelsEntry(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            key: typing___Text = ...
            value: typing___Text = ...
            def __init__(
                self,
                *,
                key: typing___Optional[typing___Text] = None,
                value: typing___Optional[typing___Text] = None,
            ) -> None: ...
            def ClearField(
                self,
                field_name: typing_extensions___Literal[
                    "key", b"key", "value", b"value"
                ],
            ) -> None: ...
        type___LabelsEntry = LabelsEntry

        service: typing___Text = ...
        name: typing___Text = ...
        type: typing___Text = ...
        @property
        def labels(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...
        def __init__(
            self,
            *,
            service: typing___Optional[typing___Text] = None,
            name: typing___Optional[typing___Text] = None,
            type: typing___Optional[typing___Text] = None,
            labels: typing___Optional[
                typing___Mapping[typing___Text, typing___Text]
            ] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "labels",
                b"labels",
                "name",
                b"name",
                "service",
                b"service",
                "type",
                b"type",
            ],
        ) -> None: ...
    type___Resource = Resource
    @property
    def origin(self) -> type___AttributeContext.Peer: ...
    @property
    def source(self) -> type___AttributeContext.Peer: ...
    @property
    def destination(self) -> type___AttributeContext.Peer: ...
    @property
    def request(self) -> type___AttributeContext.Request: ...
    @property
    def response(self) -> type___AttributeContext.Response: ...
    @property
    def resource(self) -> type___AttributeContext.Resource: ...
    @property
    def api(self) -> type___AttributeContext.Api: ...
    def __init__(
        self,
        *,
        origin: typing___Optional[type___AttributeContext.Peer] = None,
        source: typing___Optional[type___AttributeContext.Peer] = None,
        destination: typing___Optional[type___AttributeContext.Peer] = None,
        request: typing___Optional[type___AttributeContext.Request] = None,
        response: typing___Optional[type___AttributeContext.Response] = None,
        resource: typing___Optional[type___AttributeContext.Resource] = None,
        api: typing___Optional[type___AttributeContext.Api] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "api",
            b"api",
            "destination",
            b"destination",
            "origin",
            b"origin",
            "request",
            b"request",
            "resource",
            b"resource",
            "response",
            b"response",
            "source",
            b"source",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "api",
            b"api",
            "destination",
            b"destination",
            "origin",
            b"origin",
            "request",
            b"request",
            "resource",
            b"resource",
            "response",
            b"response",
            "source",
            b"source",
        ],
    ) -> None: ...

type___AttributeContext = AttributeContext
