# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.duration_pb2 import (
    Duration as google___protobuf___duration_pb2___Duration,
)
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class RetryInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def retry_delay(self) -> google___protobuf___duration_pb2___Duration: ...
    def __init__(
        self,
        *,
        retry_delay: typing___Optional[
            google___protobuf___duration_pb2___Duration
        ] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["retry_delay", b"retry_delay"]
    ) -> builtin___bool: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["retry_delay", b"retry_delay"]
    ) -> None: ...

type___RetryInfo = RetryInfo

class DebugInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    stack_entries: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
        typing___Text
    ] = ...
    detail: typing___Text = ...
    def __init__(
        self,
        *,
        stack_entries: typing___Optional[typing___Iterable[typing___Text]] = None,
        detail: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "detail", b"detail", "stack_entries", b"stack_entries"
        ],
    ) -> None: ...

type___DebugInfo = DebugInfo

class QuotaFailure(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Violation(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        subject: typing___Text = ...
        description: typing___Text = ...
        def __init__(
            self,
            *,
            subject: typing___Optional[typing___Text] = None,
            description: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "description", b"description", "subject", b"subject"
            ],
        ) -> None: ...
    type___Violation = Violation
    @property
    def violations(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___QuotaFailure.Violation
    ]: ...
    def __init__(
        self,
        *,
        violations: typing___Optional[
            typing___Iterable[type___QuotaFailure.Violation]
        ] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["violations", b"violations"]
    ) -> None: ...

type___QuotaFailure = QuotaFailure

class ErrorInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class MetadataEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: typing___Text = ...
        def __init__(
            self,
            *,
            key: typing___Optional[typing___Text] = None,
            value: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    type___MetadataEntry = MetadataEntry

    reason: typing___Text = ...
    domain: typing___Text = ...
    @property
    def metadata(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...
    def __init__(
        self,
        *,
        reason: typing___Optional[typing___Text] = None,
        domain: typing___Optional[typing___Text] = None,
        metadata: typing___Optional[
            typing___Mapping[typing___Text, typing___Text]
        ] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "domain", b"domain", "metadata", b"metadata", "reason", b"reason"
        ],
    ) -> None: ...

type___ErrorInfo = ErrorInfo

class PreconditionFailure(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Violation(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        type: typing___Text = ...
        subject: typing___Text = ...
        description: typing___Text = ...
        def __init__(
            self,
            *,
            type: typing___Optional[typing___Text] = None,
            subject: typing___Optional[typing___Text] = None,
            description: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "description", b"description", "subject", b"subject", "type", b"type"
            ],
        ) -> None: ...
    type___Violation = Violation
    @property
    def violations(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___PreconditionFailure.Violation
    ]: ...
    def __init__(
        self,
        *,
        violations: typing___Optional[
            typing___Iterable[type___PreconditionFailure.Violation]
        ] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["violations", b"violations"]
    ) -> None: ...

type___PreconditionFailure = PreconditionFailure

class BadRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class FieldViolation(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        field: typing___Text = ...
        description: typing___Text = ...
        def __init__(
            self,
            *,
            field: typing___Optional[typing___Text] = None,
            description: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "description", b"description", "field", b"field"
            ],
        ) -> None: ...
    type___FieldViolation = FieldViolation
    @property
    def field_violations(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___BadRequest.FieldViolation
    ]: ...
    def __init__(
        self,
        *,
        field_violations: typing___Optional[
            typing___Iterable[type___BadRequest.FieldViolation]
        ] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "field_violations", b"field_violations"
        ],
    ) -> None: ...

type___BadRequest = BadRequest

class RequestInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    request_id: typing___Text = ...
    serving_data: typing___Text = ...
    def __init__(
        self,
        *,
        request_id: typing___Optional[typing___Text] = None,
        serving_data: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "request_id", b"request_id", "serving_data", b"serving_data"
        ],
    ) -> None: ...

type___RequestInfo = RequestInfo

class ResourceInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    resource_type: typing___Text = ...
    resource_name: typing___Text = ...
    owner: typing___Text = ...
    description: typing___Text = ...
    def __init__(
        self,
        *,
        resource_type: typing___Optional[typing___Text] = None,
        resource_name: typing___Optional[typing___Text] = None,
        owner: typing___Optional[typing___Text] = None,
        description: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "description",
            b"description",
            "owner",
            b"owner",
            "resource_name",
            b"resource_name",
            "resource_type",
            b"resource_type",
        ],
    ) -> None: ...

type___ResourceInfo = ResourceInfo

class Help(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Link(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        description: typing___Text = ...
        url: typing___Text = ...
        def __init__(
            self,
            *,
            description: typing___Optional[typing___Text] = None,
            url: typing___Optional[typing___Text] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "description", b"description", "url", b"url"
            ],
        ) -> None: ...
    type___Link = Link
    @property
    def links(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___Help.Link
    ]: ...
    def __init__(
        self,
        *,
        links: typing___Optional[typing___Iterable[type___Help.Link]] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["links", b"links"]
    ) -> None: ...

type___Help = Help

class LocalizedMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    locale: typing___Text = ...
    message: typing___Text = ...
    def __init__(
        self,
        *,
        locale: typing___Optional[typing___Text] = None,
        message: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "locale", b"locale", "message", b"message"
        ],
    ) -> None: ...

type___LocalizedMessage = LocalizedMessage
