# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Authentication(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def rules(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___AuthenticationRule
    ]: ...
    @property
    def providers(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___AuthProvider
    ]: ...
    def __init__(
        self,
        *,
        rules: typing___Optional[typing___Iterable[type___AuthenticationRule]] = None,
        providers: typing___Optional[typing___Iterable[type___AuthProvider]] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "providers", b"providers", "rules", b"rules"
        ],
    ) -> None: ...

type___Authentication = Authentication

class AuthenticationRule(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    selector: typing___Text = ...
    allow_without_credential: builtin___bool = ...
    @property
    def oauth(self) -> type___OAuthRequirements: ...
    @property
    def requirements(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___AuthRequirement
    ]: ...
    def __init__(
        self,
        *,
        selector: typing___Optional[typing___Text] = None,
        oauth: typing___Optional[type___OAuthRequirements] = None,
        allow_without_credential: typing___Optional[builtin___bool] = None,
        requirements: typing___Optional[
            typing___Iterable[type___AuthRequirement]
        ] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["oauth", b"oauth"]
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "allow_without_credential",
            b"allow_without_credential",
            "oauth",
            b"oauth",
            "requirements",
            b"requirements",
            "selector",
            b"selector",
        ],
    ) -> None: ...

type___AuthenticationRule = AuthenticationRule

class AuthProvider(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: typing___Text = ...
    issuer: typing___Text = ...
    jwks_uri: typing___Text = ...
    audiences: typing___Text = ...
    authorization_url: typing___Text = ...
    def __init__(
        self,
        *,
        id: typing___Optional[typing___Text] = None,
        issuer: typing___Optional[typing___Text] = None,
        jwks_uri: typing___Optional[typing___Text] = None,
        audiences: typing___Optional[typing___Text] = None,
        authorization_url: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "audiences",
            b"audiences",
            "authorization_url",
            b"authorization_url",
            "id",
            b"id",
            "issuer",
            b"issuer",
            "jwks_uri",
            b"jwks_uri",
        ],
    ) -> None: ...

type___AuthProvider = AuthProvider

class OAuthRequirements(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    canonical_scopes: typing___Text = ...
    def __init__(
        self,
        *,
        canonical_scopes: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "canonical_scopes", b"canonical_scopes"
        ],
    ) -> None: ...

type___OAuthRequirements = OAuthRequirements

class AuthRequirement(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    provider_id: typing___Text = ...
    audiences: typing___Text = ...
    def __init__(
        self,
        *,
        provider_id: typing___Optional[typing___Text] = None,
        audiences: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "audiences", b"audiences", "provider_id", b"provider_id"
        ],
    ) -> None: ...

type___AuthRequirement = AuthRequirement
