# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)


method_signature = ... # type: google___protobuf___descriptor___FieldDescriptor

default_host = ... # type: google___protobuf___descriptor___FieldDescriptor

oauth_scopes = ... # type: google___protobuf___descriptor___FieldDescriptor
