"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___ChangeType = ChangeType

class _ChangeType(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ChangeType.V],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    CHANGE_TYPE_UNSPECIFIED = ChangeType.V(0)
    ADDED = ChangeType.V(1)
    REMOVED = ChangeType.V(2)
    MODIFIED = ChangeType.V(3)

class ChangeType(metaclass=_ChangeType):
    V = typing.NewType("V", builtins.int)

CHANGE_TYPE_UNSPECIFIED = ChangeType.V(0)
ADDED = ChangeType.V(1)
REMOVED = ChangeType.V(2)
MODIFIED = ChangeType.V(3)

class ConfigChange(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ELEMENT_FIELD_NUMBER: builtins.int
    OLD_VALUE_FIELD_NUMBER: builtins.int
    NEW_VALUE_FIELD_NUMBER: builtins.int
    CHANGE_TYPE_FIELD_NUMBER: builtins.int
    ADVICES_FIELD_NUMBER: builtins.int
    element: typing.Text = ...
    old_value: typing.Text = ...
    new_value: typing.Text = ...
    change_type: global___ChangeType.V = ...
    @property
    def advices(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Advice
    ]: ...
    def __init__(
        self,
        *,
        element: typing.Text = ...,
        old_value: typing.Text = ...,
        new_value: typing.Text = ...,
        change_type: global___ChangeType.V = ...,
        advices: typing.Optional[typing.Iterable[global___Advice]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "advices",
            b"advices",
            "change_type",
            b"change_type",
            "element",
            b"element",
            "new_value",
            b"new_value",
            "old_value",
            b"old_value",
        ],
    ) -> None: ...

global___ConfigChange = ConfigChange

class Advice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DESCRIPTION_FIELD_NUMBER: builtins.int
    description: typing.Text = ...
    def __init__(
        self,
        *,
        description: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["description", b"description"]
    ) -> None: ...

global___Advice = Advice
