# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import Iterable as typing___Iterable, Optional as typing___Optional

from google.protobuf.any_pb2 import Any as google___protobuf___any_pb2___Any
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)
from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Distribution(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Range(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        min: builtin___float = ...
        max: builtin___float = ...
        def __init__(
            self,
            *,
            min: typing___Optional[builtin___float] = None,
            max: typing___Optional[builtin___float] = None,
        ) -> None: ...
        def ClearField(
            self, field_name: typing_extensions___Literal["max", b"max", "min", b"min"]
        ) -> None: ...
    type___Range = Range
    class BucketOptions(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class Linear(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            num_finite_buckets: builtin___int = ...
            width: builtin___float = ...
            offset: builtin___float = ...
            def __init__(
                self,
                *,
                num_finite_buckets: typing___Optional[builtin___int] = None,
                width: typing___Optional[builtin___float] = None,
                offset: typing___Optional[builtin___float] = None,
            ) -> None: ...
            def ClearField(
                self,
                field_name: typing_extensions___Literal[
                    "num_finite_buckets",
                    b"num_finite_buckets",
                    "offset",
                    b"offset",
                    "width",
                    b"width",
                ],
            ) -> None: ...
        type___Linear = Linear
        class Exponential(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            num_finite_buckets: builtin___int = ...
            growth_factor: builtin___float = ...
            scale: builtin___float = ...
            def __init__(
                self,
                *,
                num_finite_buckets: typing___Optional[builtin___int] = None,
                growth_factor: typing___Optional[builtin___float] = None,
                scale: typing___Optional[builtin___float] = None,
            ) -> None: ...
            def ClearField(
                self,
                field_name: typing_extensions___Literal[
                    "growth_factor",
                    b"growth_factor",
                    "num_finite_buckets",
                    b"num_finite_buckets",
                    "scale",
                    b"scale",
                ],
            ) -> None: ...
        type___Exponential = Exponential
        class Explicit(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            bounds: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
                builtin___float
            ] = ...
            def __init__(
                self,
                *,
                bounds: typing___Optional[typing___Iterable[builtin___float]] = None,
            ) -> None: ...
            def ClearField(
                self, field_name: typing_extensions___Literal["bounds", b"bounds"]
            ) -> None: ...
        type___Explicit = Explicit
        @property
        def linear_buckets(self) -> type___Distribution.BucketOptions.Linear: ...
        @property
        def exponential_buckets(
            self,
        ) -> type___Distribution.BucketOptions.Exponential: ...
        @property
        def explicit_buckets(self) -> type___Distribution.BucketOptions.Explicit: ...
        def __init__(
            self,
            *,
            linear_buckets: typing___Optional[
                type___Distribution.BucketOptions.Linear
            ] = None,
            exponential_buckets: typing___Optional[
                type___Distribution.BucketOptions.Exponential
            ] = None,
            explicit_buckets: typing___Optional[
                type___Distribution.BucketOptions.Explicit
            ] = None,
        ) -> None: ...
        def HasField(
            self,
            field_name: typing_extensions___Literal[
                "explicit_buckets",
                b"explicit_buckets",
                "exponential_buckets",
                b"exponential_buckets",
                "linear_buckets",
                b"linear_buckets",
                "options",
                b"options",
            ],
        ) -> builtin___bool: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "explicit_buckets",
                b"explicit_buckets",
                "exponential_buckets",
                b"exponential_buckets",
                "linear_buckets",
                b"linear_buckets",
                "options",
                b"options",
            ],
        ) -> None: ...
        def WhichOneof(
            self, oneof_group: typing_extensions___Literal["options", b"options"]
        ) -> typing_extensions___Literal[
            "linear_buckets", "exponential_buckets", "explicit_buckets"
        ]: ...
    type___BucketOptions = BucketOptions
    class Exemplar(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        value: builtin___float = ...
        @property
        def timestamp(self) -> google___protobuf___timestamp_pb2___Timestamp: ...
        @property
        def attachments(
            self,
        ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
            google___protobuf___any_pb2___Any
        ]: ...
        def __init__(
            self,
            *,
            value: typing___Optional[builtin___float] = None,
            timestamp: typing___Optional[
                google___protobuf___timestamp_pb2___Timestamp
            ] = None,
            attachments: typing___Optional[
                typing___Iterable[google___protobuf___any_pb2___Any]
            ] = None,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions___Literal["timestamp", b"timestamp"]
        ) -> builtin___bool: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "attachments",
                b"attachments",
                "timestamp",
                b"timestamp",
                "value",
                b"value",
            ],
        ) -> None: ...
    type___Exemplar = Exemplar

    count: builtin___int = ...
    mean: builtin___float = ...
    sum_of_squared_deviation: builtin___float = ...
    bucket_counts: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
        builtin___int
    ] = ...
    @property
    def range(self) -> type___Distribution.Range: ...
    @property
    def bucket_options(self) -> type___Distribution.BucketOptions: ...
    @property
    def exemplars(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___Distribution.Exemplar
    ]: ...
    def __init__(
        self,
        *,
        count: typing___Optional[builtin___int] = None,
        mean: typing___Optional[builtin___float] = None,
        sum_of_squared_deviation: typing___Optional[builtin___float] = None,
        range: typing___Optional[type___Distribution.Range] = None,
        bucket_options: typing___Optional[type___Distribution.BucketOptions] = None,
        bucket_counts: typing___Optional[typing___Iterable[builtin___int]] = None,
        exemplars: typing___Optional[
            typing___Iterable[type___Distribution.Exemplar]
        ] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "bucket_options", b"bucket_options", "range", b"range"
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "bucket_counts",
            b"bucket_counts",
            "bucket_options",
            b"bucket_options",
            "count",
            b"count",
            "exemplars",
            b"exemplars",
            "mean",
            b"mean",
            "range",
            b"range",
            "sum_of_squared_deviation",
            b"sum_of_squared_deviation",
        ],
    ) -> None: ...

type___Distribution = Distribution
