"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Documentation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SUMMARY_FIELD_NUMBER: builtins.int
    PAGES_FIELD_NUMBER: builtins.int
    RULES_FIELD_NUMBER: builtins.int
    DOCUMENTATION_ROOT_URL_FIELD_NUMBER: builtins.int
    OVERVIEW_FIELD_NUMBER: builtins.int
    summary: typing.Text = ...
    documentation_root_url: typing.Text = ...
    overview: typing.Text = ...
    @property
    def pages(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Page
    ]: ...
    @property
    def rules(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___DocumentationRule
    ]: ...
    def __init__(
        self,
        *,
        summary: typing.Text = ...,
        pages: typing.Optional[typing.Iterable[global___Page]] = ...,
        rules: typing.Optional[typing.Iterable[global___DocumentationRule]] = ...,
        documentation_root_url: typing.Text = ...,
        overview: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "documentation_root_url",
            b"documentation_root_url",
            "overview",
            b"overview",
            "pages",
            b"pages",
            "rules",
            b"rules",
            "summary",
            b"summary",
        ],
    ) -> None: ...

global___Documentation = Documentation

class DocumentationRule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SELECTOR_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    DEPRECATION_DESCRIPTION_FIELD_NUMBER: builtins.int
    selector: typing.Text = ...
    description: typing.Text = ...
    deprecation_description: typing.Text = ...
    def __init__(
        self,
        *,
        selector: typing.Text = ...,
        description: typing.Text = ...,
        deprecation_description: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "deprecation_description",
            b"deprecation_description",
            "description",
            b"description",
            "selector",
            b"selector",
        ],
    ) -> None: ...

global___DocumentationRule = DocumentationRule

class Page(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    SUBPAGES_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    content: typing.Text = ...
    @property
    def subpages(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Page
    ]: ...
    def __init__(
        self,
        *,
        name: typing.Text = ...,
        content: typing.Text = ...,
        subpages: typing.Optional[typing.Iterable[global___Page]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "content", b"content", "name", b"name", "subpages", b"subpages"
        ],
    ) -> None: ...

global___Page = Page
