# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Endpoint(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    aliases: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
        typing___Text
    ] = ...
    features: google___protobuf___internal___containers___RepeatedScalarFieldContainer[
        typing___Text
    ] = ...
    target: typing___Text = ...
    allow_cors: builtin___bool = ...
    def __init__(
        self,
        *,
        name: typing___Optional[typing___Text] = None,
        aliases: typing___Optional[typing___Iterable[typing___Text]] = None,
        features: typing___Optional[typing___Iterable[typing___Text]] = None,
        target: typing___Optional[typing___Text] = None,
        allow_cors: typing___Optional[builtin___bool] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "aliases",
            b"aliases",
            "allow_cors",
            b"allow_cors",
            "features",
            b"features",
            "name",
            b"name",
            "target",
            b"target",
        ],
    ) -> None: ...

type___Endpoint = Endpoint
