"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Endpoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    ALIASES_FIELD_NUMBER: builtins.int
    FEATURES_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    ALLOW_CORS_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    aliases: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    features: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    target: typing.Text = ...
    allow_cors: builtins.bool = ...
    def __init__(
        self,
        *,
        name: typing.Text = ...,
        aliases: typing.Optional[typing.Iterable[typing.Text]] = ...,
        features: typing.Optional[typing.Iterable[typing.Text]] = ...,
        target: typing.Text = ...,
        allow_cors: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "aliases",
            b"aliases",
            "allow_cors",
            b"allow_cors",
            "features",
            b"features",
            "name",
            b"name",
            "target",
            b"target",
        ],
    ) -> None: ...

global___Endpoint = Endpoint
