# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Tuple as typing___Tuple,
    cast as typing___cast,
)


class FieldBehavior(int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> FieldBehavior: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[FieldBehavior]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, FieldBehavior]]: ...
    FIELD_BEHAVIOR_UNSPECIFIED = typing___cast(FieldBehavior, 0)
    OPTIONAL = typing___cast(FieldBehavior, 1)
    REQUIRED = typing___cast(FieldBehavior, 2)
    OUTPUT_ONLY = typing___cast(FieldBehavior, 3)
    INPUT_ONLY = typing___cast(FieldBehavior, 4)
    IMMUTABLE = typing___cast(FieldBehavior, 5)
FIELD_BEHAVIOR_UNSPECIFIED = typing___cast(FieldBehavior, 0)
OPTIONAL = typing___cast(FieldBehavior, 1)
REQUIRED = typing___cast(FieldBehavior, 2)
OUTPUT_ONLY = typing___cast(FieldBehavior, 3)
INPUT_ONLY = typing___cast(FieldBehavior, 4)
IMMUTABLE = typing___cast(FieldBehavior, 5)

field_behavior = ... # type: google___protobuf___descriptor___FieldDescriptor
