# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Http(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    fully_decode_reserved_expansion = ... # type: bool

    @property
    def rules(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[HttpRule]: ...

    def __init__(self,
        *,
        rules : typing___Optional[typing___Iterable[HttpRule]] = None,
        fully_decode_reserved_expansion : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Http: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"fully_decode_reserved_expansion",u"rules"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"fully_decode_reserved_expansion",b"fully_decode_reserved_expansion",u"rules",b"rules"]) -> None: ...

class HttpRule(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    selector = ... # type: typing___Text
    get = ... # type: typing___Text
    put = ... # type: typing___Text
    post = ... # type: typing___Text
    delete = ... # type: typing___Text
    patch = ... # type: typing___Text
    body = ... # type: typing___Text
    response_body = ... # type: typing___Text

    @property
    def custom(self) -> CustomHttpPattern: ...

    @property
    def additional_bindings(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[HttpRule]: ...

    def __init__(self,
        *,
        selector : typing___Optional[typing___Text] = None,
        get : typing___Optional[typing___Text] = None,
        put : typing___Optional[typing___Text] = None,
        post : typing___Optional[typing___Text] = None,
        delete : typing___Optional[typing___Text] = None,
        patch : typing___Optional[typing___Text] = None,
        custom : typing___Optional[CustomHttpPattern] = None,
        body : typing___Optional[typing___Text] = None,
        response_body : typing___Optional[typing___Text] = None,
        additional_bindings : typing___Optional[typing___Iterable[HttpRule]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> HttpRule: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"custom",u"delete",u"get",u"patch",u"pattern",u"post",u"put"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"additional_bindings",u"body",u"custom",u"delete",u"get",u"patch",u"pattern",u"post",u"put",u"response_body",u"selector"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"custom",b"custom",u"delete",b"delete",u"get",b"get",u"patch",b"patch",u"pattern",b"pattern",u"post",b"post",u"put",b"put"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"additional_bindings",b"additional_bindings",u"body",b"body",u"custom",b"custom",u"delete",b"delete",u"get",b"get",u"patch",b"patch",u"pattern",b"pattern",u"post",b"post",u"put",b"put",u"response_body",b"response_body",u"selector",b"selector"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"pattern",b"pattern"]) -> typing_extensions___Literal["get","put","post","delete","patch","custom"]: ...

class CustomHttpPattern(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    kind = ... # type: typing___Text
    path = ... # type: typing___Text

    def __init__(self,
        *,
        kind : typing___Optional[typing___Text] = None,
        path : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> CustomHttpPattern: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"kind",u"path"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"kind",b"kind",u"path",b"path"]) -> None: ...
