"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class LabelDescriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _ValueType(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ValueType.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        STRING = LabelDescriptor.ValueType.V(0)
        BOOL = LabelDescriptor.ValueType.V(1)
        INT64 = LabelDescriptor.ValueType.V(2)
    class ValueType(metaclass=_ValueType):
        V = typing.NewType("V", builtins.int)
    STRING = LabelDescriptor.ValueType.V(0)
    BOOL = LabelDescriptor.ValueType.V(1)
    INT64 = LabelDescriptor.ValueType.V(2)

    KEY_FIELD_NUMBER: builtins.int
    VALUE_TYPE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    key: typing.Text = ...
    value_type: global___LabelDescriptor.ValueType.V = ...
    description: typing.Text = ...
    def __init__(
        self,
        *,
        key: typing.Text = ...,
        value_type: global___LabelDescriptor.ValueType.V = ...,
        description: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "description", b"description", "key", b"key", "value_type", b"value_type"
        ],
    ) -> None: ...

global___LabelDescriptor = LabelDescriptor
