"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___LaunchStage = LaunchStage

class _LaunchStage(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LaunchStage.V],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    LAUNCH_STAGE_UNSPECIFIED = LaunchStage.V(0)
    EARLY_ACCESS = LaunchStage.V(1)
    ALPHA = LaunchStage.V(2)
    BETA = LaunchStage.V(3)
    GA = LaunchStage.V(4)
    DEPRECATED = LaunchStage.V(5)

class LaunchStage(metaclass=_LaunchStage):
    V = typing.NewType("V", builtins.int)

LAUNCH_STAGE_UNSPECIFIED = LaunchStage.V(0)
EARLY_ACCESS = LaunchStage.V(1)
ALPHA = LaunchStage.V(2)
BETA = LaunchStage.V(3)
GA = LaunchStage.V(4)
DEPRECATED = LaunchStage.V(5)
