# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

LaunchStageValue = typing___NewType("LaunchStageValue", builtin___int)
type___LaunchStageValue = LaunchStageValue
LaunchStage: _LaunchStage

class _LaunchStage(
    google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
        LaunchStageValue
    ]
):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    LAUNCH_STAGE_UNSPECIFIED = typing___cast(LaunchStageValue, 0)
    EARLY_ACCESS = typing___cast(LaunchStageValue, 1)
    ALPHA = typing___cast(LaunchStageValue, 2)
    BETA = typing___cast(LaunchStageValue, 3)
    GA = typing___cast(LaunchStageValue, 4)
    DEPRECATED = typing___cast(LaunchStageValue, 5)

LAUNCH_STAGE_UNSPECIFIED = typing___cast(LaunchStageValue, 0)
EARLY_ACCESS = typing___cast(LaunchStageValue, 1)
ALPHA = typing___cast(LaunchStageValue, 2)
BETA = typing___cast(LaunchStageValue, 3)
GA = typing___cast(LaunchStageValue, 4)
DEPRECATED = typing___cast(LaunchStageValue, 5)
type___LaunchStage = LaunchStage
