# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.api.label_pb2 import (
    LabelDescriptor as google___api___label_pb2___LabelDescriptor,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class LogDescriptor(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    description = ... # type: typing___Text
    display_name = ... # type: typing___Text

    @property
    def labels(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___api___label_pb2___LabelDescriptor]: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        labels : typing___Optional[typing___Iterable[google___api___label_pb2___LabelDescriptor]] = None,
        description : typing___Optional[typing___Text] = None,
        display_name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> LogDescriptor: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"description",u"display_name",u"labels",u"name"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"description",b"description",u"display_name",b"display_name",u"labels",b"labels",u"name",b"name"]) -> None: ...
