# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Logging(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class LoggingDestination(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        monitored_resource = ... # type: typing___Text
        logs = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

        def __init__(self,
            *,
            monitored_resource : typing___Optional[typing___Text] = None,
            logs : typing___Optional[typing___Iterable[typing___Text]] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> Logging.LoggingDestination: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def ClearField(self, field_name: typing_extensions___Literal[u"logs",u"monitored_resource"]) -> None: ...
        else:
            def ClearField(self, field_name: typing_extensions___Literal[u"logs",b"logs",u"monitored_resource",b"monitored_resource"]) -> None: ...


    @property
    def producer_destinations(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Logging.LoggingDestination]: ...

    @property
    def consumer_destinations(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Logging.LoggingDestination]: ...

    def __init__(self,
        *,
        producer_destinations : typing___Optional[typing___Iterable[Logging.LoggingDestination]] = None,
        consumer_destinations : typing___Optional[typing___Iterable[Logging.LoggingDestination]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Logging: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"consumer_destinations",u"producer_destinations"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"consumer_destinations",b"consumer_destinations",u"producer_destinations",b"producer_destinations"]) -> None: ...
