"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.api.label_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class MetricDescriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _MetricKind(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MetricKind.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        METRIC_KIND_UNSPECIFIED = MetricDescriptor.MetricKind.V(0)
        GAUGE = MetricDescriptor.MetricKind.V(1)
        DELTA = MetricDescriptor.MetricKind.V(2)
        CUMULATIVE = MetricDescriptor.MetricKind.V(3)
    class MetricKind(metaclass=_MetricKind):
        V = typing.NewType("V", builtins.int)
    METRIC_KIND_UNSPECIFIED = MetricDescriptor.MetricKind.V(0)
    GAUGE = MetricDescriptor.MetricKind.V(1)
    DELTA = MetricDescriptor.MetricKind.V(2)
    CUMULATIVE = MetricDescriptor.MetricKind.V(3)
    class _ValueType(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ValueType.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        VALUE_TYPE_UNSPECIFIED = MetricDescriptor.ValueType.V(0)
        BOOL = MetricDescriptor.ValueType.V(1)
        INT64 = MetricDescriptor.ValueType.V(2)
        DOUBLE = MetricDescriptor.ValueType.V(3)
        STRING = MetricDescriptor.ValueType.V(4)
        DISTRIBUTION = MetricDescriptor.ValueType.V(5)
        MONEY = MetricDescriptor.ValueType.V(6)
    class ValueType(metaclass=_ValueType):
        V = typing.NewType("V", builtins.int)
    VALUE_TYPE_UNSPECIFIED = MetricDescriptor.ValueType.V(0)
    BOOL = MetricDescriptor.ValueType.V(1)
    INT64 = MetricDescriptor.ValueType.V(2)
    DOUBLE = MetricDescriptor.ValueType.V(3)
    STRING = MetricDescriptor.ValueType.V(4)
    DISTRIBUTION = MetricDescriptor.ValueType.V(5)
    MONEY = MetricDescriptor.ValueType.V(6)

    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    METRIC_KIND_FIELD_NUMBER: builtins.int
    VALUE_TYPE_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    type: typing.Text = ...
    metric_kind: global___MetricDescriptor.MetricKind.V = ...
    value_type: global___MetricDescriptor.ValueType.V = ...
    unit: typing.Text = ...
    description: typing.Text = ...
    display_name: typing.Text = ...
    @property
    def labels(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        google.api.label_pb2.LabelDescriptor
    ]: ...
    def __init__(
        self,
        *,
        name: typing.Text = ...,
        type: typing.Text = ...,
        labels: typing.Optional[
            typing.Iterable[google.api.label_pb2.LabelDescriptor]
        ] = ...,
        metric_kind: global___MetricDescriptor.MetricKind.V = ...,
        value_type: global___MetricDescriptor.ValueType.V = ...,
        unit: typing.Text = ...,
        description: typing.Text = ...,
        display_name: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "description",
            b"description",
            "display_name",
            b"display_name",
            "labels",
            b"labels",
            "metric_kind",
            b"metric_kind",
            "name",
            b"name",
            "type",
            b"type",
            "unit",
            b"unit",
            "value_type",
            b"value_type",
        ],
    ) -> None: ...

global___MetricDescriptor = MetricDescriptor

class Metric(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...
        def __init__(
            self,
            *,
            key: typing.Text = ...,
            value: typing.Text = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions.Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    TYPE_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    type: typing.Text = ...
    @property
    def labels(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
    def __init__(
        self,
        *,
        type: typing.Text = ...,
        labels: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal["labels", b"labels", "type", b"type"],
    ) -> None: ...

global___Metric = Metric
