# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.api.label_pb2 import (
    LabelDescriptor as google___api___label_pb2___LabelDescriptor,
)

from google.api.launch_stage_pb2 import (
    LaunchStage as google___api___launch_stage_pb2___LaunchStage,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.struct_pb2 import (
    Struct as google___protobuf___struct_pb2___Struct,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class MonitoredResourceDescriptor(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    type = ... # type: typing___Text
    display_name = ... # type: typing___Text
    description = ... # type: typing___Text
    launch_stage = ... # type: google___api___launch_stage_pb2___LaunchStage

    @property
    def labels(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___api___label_pb2___LabelDescriptor]: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        type : typing___Optional[typing___Text] = None,
        display_name : typing___Optional[typing___Text] = None,
        description : typing___Optional[typing___Text] = None,
        labels : typing___Optional[typing___Iterable[google___api___label_pb2___LabelDescriptor]] = None,
        launch_stage : typing___Optional[google___api___launch_stage_pb2___LaunchStage] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> MonitoredResourceDescriptor: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"description",u"display_name",u"labels",u"launch_stage",u"name",u"type"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"description",b"description",u"display_name",b"display_name",u"labels",b"labels",u"launch_stage",b"launch_stage",u"name",b"name",u"type",b"type"]) -> None: ...

class MonitoredResource(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class LabelsEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key = ... # type: typing___Text
        value = ... # type: typing___Text

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> MonitoredResource.LabelsEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def ClearField(self, field_name: typing_extensions___Literal[u"key",u"value"]) -> None: ...
        else:
            def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    type = ... # type: typing___Text

    @property
    def labels(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

    def __init__(self,
        *,
        type : typing___Optional[typing___Text] = None,
        labels : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> MonitoredResource: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"labels",u"type"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"labels",b"labels",u"type",b"type"]) -> None: ...

class MonitoredResourceMetadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class UserLabelsEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key = ... # type: typing___Text
        value = ... # type: typing___Text

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> MonitoredResourceMetadata.UserLabelsEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def ClearField(self, field_name: typing_extensions___Literal[u"key",u"value"]) -> None: ...
        else:
            def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...


    @property
    def system_labels(self) -> google___protobuf___struct_pb2___Struct: ...

    @property
    def user_labels(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

    def __init__(self,
        *,
        system_labels : typing___Optional[google___protobuf___struct_pb2___Struct] = None,
        user_labels : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> MonitoredResourceMetadata: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"system_labels"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"system_labels",u"user_labels"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"system_labels",b"system_labels"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"system_labels",b"system_labels",u"user_labels",b"user_labels"]) -> None: ...
