# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Quota(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def limits(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___QuotaLimit
    ]: ...
    @property
    def metric_rules(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___MetricRule
    ]: ...
    def __init__(
        self,
        *,
        limits: typing___Optional[typing___Iterable[type___QuotaLimit]] = None,
        metric_rules: typing___Optional[typing___Iterable[type___MetricRule]] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "limits", b"limits", "metric_rules", b"metric_rules"
        ],
    ) -> None: ...

type___Quota = Quota

class MetricRule(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class MetricCostsEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: builtin___int = ...
        def __init__(
            self,
            *,
            key: typing___Optional[typing___Text] = None,
            value: typing___Optional[builtin___int] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    type___MetricCostsEntry = MetricCostsEntry

    selector: typing___Text = ...
    @property
    def metric_costs(self) -> typing___MutableMapping[typing___Text, builtin___int]: ...
    def __init__(
        self,
        *,
        selector: typing___Optional[typing___Text] = None,
        metric_costs: typing___Optional[
            typing___Mapping[typing___Text, builtin___int]
        ] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "metric_costs", b"metric_costs", "selector", b"selector"
        ],
    ) -> None: ...

type___MetricRule = MetricRule

class QuotaLimit(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class ValuesEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: builtin___int = ...
        def __init__(
            self,
            *,
            key: typing___Optional[typing___Text] = None,
            value: typing___Optional[builtin___int] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal["key", b"key", "value", b"value"],
        ) -> None: ...
    type___ValuesEntry = ValuesEntry

    name: typing___Text = ...
    description: typing___Text = ...
    default_limit: builtin___int = ...
    max_limit: builtin___int = ...
    free_tier: builtin___int = ...
    duration: typing___Text = ...
    metric: typing___Text = ...
    unit: typing___Text = ...
    display_name: typing___Text = ...
    @property
    def values(self) -> typing___MutableMapping[typing___Text, builtin___int]: ...
    def __init__(
        self,
        *,
        name: typing___Optional[typing___Text] = None,
        description: typing___Optional[typing___Text] = None,
        default_limit: typing___Optional[builtin___int] = None,
        max_limit: typing___Optional[builtin___int] = None,
        free_tier: typing___Optional[builtin___int] = None,
        duration: typing___Optional[typing___Text] = None,
        metric: typing___Optional[typing___Text] = None,
        unit: typing___Optional[typing___Text] = None,
        values: typing___Optional[
            typing___Mapping[typing___Text, builtin___int]
        ] = None,
        display_name: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "default_limit",
            b"default_limit",
            "description",
            b"description",
            "display_name",
            b"display_name",
            "duration",
            b"duration",
            "free_tier",
            b"free_tier",
            "max_limit",
            b"max_limit",
            "metric",
            b"metric",
            "name",
            b"name",
            "unit",
            b"unit",
            "values",
            b"values",
        ],
    ) -> None: ...

type___QuotaLimit = QuotaLimit
