"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ResourceDescriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _History(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[History.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        HISTORY_UNSPECIFIED = ResourceDescriptor.History.V(0)
        ORIGINALLY_SINGLE_PATTERN = ResourceDescriptor.History.V(1)
        FUTURE_MULTI_PATTERN = ResourceDescriptor.History.V(2)
    class History(metaclass=_History):
        V = typing.NewType("V", builtins.int)
    HISTORY_UNSPECIFIED = ResourceDescriptor.History.V(0)
    ORIGINALLY_SINGLE_PATTERN = ResourceDescriptor.History.V(1)
    FUTURE_MULTI_PATTERN = ResourceDescriptor.History.V(2)
    class _Style(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Style.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        STYLE_UNSPECIFIED = ResourceDescriptor.Style.V(0)
        DECLARATIVE_FRIENDLY = ResourceDescriptor.Style.V(1)
    class Style(metaclass=_Style):
        V = typing.NewType("V", builtins.int)
    STYLE_UNSPECIFIED = ResourceDescriptor.Style.V(0)
    DECLARATIVE_FRIENDLY = ResourceDescriptor.Style.V(1)

    TYPE_FIELD_NUMBER: builtins.int
    PATTERN_FIELD_NUMBER: builtins.int
    NAME_FIELD_FIELD_NUMBER: builtins.int
    HISTORY_FIELD_NUMBER: builtins.int
    PLURAL_FIELD_NUMBER: builtins.int
    SINGULAR_FIELD_NUMBER: builtins.int
    STYLE_FIELD_NUMBER: builtins.int
    type: typing.Text = ...
    pattern: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    name_field: typing.Text = ...
    history: global___ResourceDescriptor.History.V = ...
    plural: typing.Text = ...
    singular: typing.Text = ...
    style: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        global___ResourceDescriptor.Style.V
    ] = ...
    def __init__(
        self,
        *,
        type: typing.Text = ...,
        pattern: typing.Optional[typing.Iterable[typing.Text]] = ...,
        name_field: typing.Text = ...,
        history: global___ResourceDescriptor.History.V = ...,
        plural: typing.Text = ...,
        singular: typing.Text = ...,
        style: typing.Optional[
            typing.Iterable[global___ResourceDescriptor.Style.V]
        ] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "history",
            b"history",
            "name_field",
            b"name_field",
            "pattern",
            b"pattern",
            "plural",
            b"plural",
            "singular",
            b"singular",
            "style",
            b"style",
            "type",
            b"type",
        ],
    ) -> None: ...

global___ResourceDescriptor = ResourceDescriptor

class ResourceReference(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TYPE_FIELD_NUMBER: builtins.int
    CHILD_TYPE_FIELD_NUMBER: builtins.int
    type: typing.Text = ...
    child_type: typing.Text = ...
    def __init__(
        self,
        *,
        type: typing.Text = ...,
        child_type: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "child_type", b"child_type", "type", b"type"
        ],
    ) -> None: ...

global___ResourceReference = ResourceReference

resource_reference: google.protobuf.descriptor.FieldDescriptor = ...

resource_definition: google.protobuf.descriptor.FieldDescriptor = ...

resource: google.protobuf.descriptor.FieldDescriptor = ...
