# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.api.auth_pb2 import (
    Authentication as google___api___auth_pb2___Authentication,
)

from google.api.backend_pb2 import (
    Backend as google___api___backend_pb2___Backend,
)

from google.api.billing_pb2 import (
    Billing as google___api___billing_pb2___Billing,
)

from google.api.context_pb2 import (
    Context as google___api___context_pb2___Context,
)

from google.api.control_pb2 import (
    Control as google___api___control_pb2___Control,
)

from google.api.documentation_pb2 import (
    Documentation as google___api___documentation_pb2___Documentation,
)

from google.api.endpoint_pb2 import (
    Endpoint as google___api___endpoint_pb2___Endpoint,
)

from google.api.http_pb2 import (
    Http as google___api___http_pb2___Http,
)

from google.api.log_pb2 import (
    LogDescriptor as google___api___log_pb2___LogDescriptor,
)

from google.api.logging_pb2 import (
    Logging as google___api___logging_pb2___Logging,
)

from google.api.metric_pb2 import (
    MetricDescriptor as google___api___metric_pb2___MetricDescriptor,
)

from google.api.monitored_resource_pb2 import (
    MonitoredResourceDescriptor as google___api___monitored_resource_pb2___MonitoredResourceDescriptor,
)

from google.api.monitoring_pb2 import (
    Monitoring as google___api___monitoring_pb2___Monitoring,
)

from google.api.quota_pb2 import (
    Quota as google___api___quota_pb2___Quota,
)

from google.api.source_info_pb2 import (
    SourceInfo as google___api___source_info_pb2___SourceInfo,
)

from google.api.system_parameter_pb2 import (
    SystemParameters as google___api___system_parameter_pb2___SystemParameters,
)

from google.api.usage_pb2 import (
    Usage as google___api___usage_pb2___Usage,
)

from google.protobuf.api_pb2 import (
    Api as google___protobuf___api_pb2___Api,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.type_pb2 import (
    Enum as google___protobuf___type_pb2___Enum,
    Type as google___protobuf___type_pb2___Type,
)

from google.protobuf.wrappers_pb2 import (
    UInt32Value as google___protobuf___wrappers_pb2___UInt32Value,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Service(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    id = ... # type: typing___Text
    title = ... # type: typing___Text
    producer_project_id = ... # type: typing___Text

    @property
    def config_version(self) -> google___protobuf___wrappers_pb2___UInt32Value: ...

    @property
    def apis(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___protobuf___api_pb2___Api]: ...

    @property
    def types(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___protobuf___type_pb2___Type]: ...

    @property
    def enums(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___protobuf___type_pb2___Enum]: ...

    @property
    def documentation(self) -> google___api___documentation_pb2___Documentation: ...

    @property
    def backend(self) -> google___api___backend_pb2___Backend: ...

    @property
    def http(self) -> google___api___http_pb2___Http: ...

    @property
    def quota(self) -> google___api___quota_pb2___Quota: ...

    @property
    def authentication(self) -> google___api___auth_pb2___Authentication: ...

    @property
    def context(self) -> google___api___context_pb2___Context: ...

    @property
    def usage(self) -> google___api___usage_pb2___Usage: ...

    @property
    def endpoints(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___api___endpoint_pb2___Endpoint]: ...

    @property
    def control(self) -> google___api___control_pb2___Control: ...

    @property
    def logs(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___api___log_pb2___LogDescriptor]: ...

    @property
    def metrics(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___api___metric_pb2___MetricDescriptor]: ...

    @property
    def monitored_resources(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___api___monitored_resource_pb2___MonitoredResourceDescriptor]: ...

    @property
    def billing(self) -> google___api___billing_pb2___Billing: ...

    @property
    def logging(self) -> google___api___logging_pb2___Logging: ...

    @property
    def monitoring(self) -> google___api___monitoring_pb2___Monitoring: ...

    @property
    def system_parameters(self) -> google___api___system_parameter_pb2___SystemParameters: ...

    @property
    def source_info(self) -> google___api___source_info_pb2___SourceInfo: ...

    def __init__(self,
        *,
        config_version : typing___Optional[google___protobuf___wrappers_pb2___UInt32Value] = None,
        name : typing___Optional[typing___Text] = None,
        id : typing___Optional[typing___Text] = None,
        title : typing___Optional[typing___Text] = None,
        producer_project_id : typing___Optional[typing___Text] = None,
        apis : typing___Optional[typing___Iterable[google___protobuf___api_pb2___Api]] = None,
        types : typing___Optional[typing___Iterable[google___protobuf___type_pb2___Type]] = None,
        enums : typing___Optional[typing___Iterable[google___protobuf___type_pb2___Enum]] = None,
        documentation : typing___Optional[google___api___documentation_pb2___Documentation] = None,
        backend : typing___Optional[google___api___backend_pb2___Backend] = None,
        http : typing___Optional[google___api___http_pb2___Http] = None,
        quota : typing___Optional[google___api___quota_pb2___Quota] = None,
        authentication : typing___Optional[google___api___auth_pb2___Authentication] = None,
        context : typing___Optional[google___api___context_pb2___Context] = None,
        usage : typing___Optional[google___api___usage_pb2___Usage] = None,
        endpoints : typing___Optional[typing___Iterable[google___api___endpoint_pb2___Endpoint]] = None,
        control : typing___Optional[google___api___control_pb2___Control] = None,
        logs : typing___Optional[typing___Iterable[google___api___log_pb2___LogDescriptor]] = None,
        metrics : typing___Optional[typing___Iterable[google___api___metric_pb2___MetricDescriptor]] = None,
        monitored_resources : typing___Optional[typing___Iterable[google___api___monitored_resource_pb2___MonitoredResourceDescriptor]] = None,
        billing : typing___Optional[google___api___billing_pb2___Billing] = None,
        logging : typing___Optional[google___api___logging_pb2___Logging] = None,
        monitoring : typing___Optional[google___api___monitoring_pb2___Monitoring] = None,
        system_parameters : typing___Optional[google___api___system_parameter_pb2___SystemParameters] = None,
        source_info : typing___Optional[google___api___source_info_pb2___SourceInfo] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Service: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"authentication",u"backend",u"billing",u"config_version",u"context",u"control",u"documentation",u"http",u"logging",u"monitoring",u"quota",u"source_info",u"system_parameters",u"usage"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"apis",u"authentication",u"backend",u"billing",u"config_version",u"context",u"control",u"documentation",u"endpoints",u"enums",u"http",u"id",u"logging",u"logs",u"metrics",u"monitored_resources",u"monitoring",u"name",u"producer_project_id",u"quota",u"source_info",u"system_parameters",u"title",u"types",u"usage"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"authentication",b"authentication",u"backend",b"backend",u"billing",b"billing",u"config_version",b"config_version",u"context",b"context",u"control",b"control",u"documentation",b"documentation",u"http",b"http",u"logging",b"logging",u"monitoring",b"monitoring",u"quota",b"quota",u"source_info",b"source_info",u"system_parameters",b"system_parameters",u"usage",b"usage"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"apis",b"apis",u"authentication",b"authentication",u"backend",b"backend",u"billing",b"billing",u"config_version",b"config_version",u"context",b"context",u"control",b"control",u"documentation",b"documentation",u"endpoints",b"endpoints",u"enums",b"enums",u"http",b"http",u"id",b"id",u"logging",b"logging",u"logs",b"logs",u"metrics",b"metrics",u"monitored_resources",b"monitored_resources",u"monitoring",b"monitoring",u"name",b"name",u"producer_project_id",b"producer_project_id",u"quota",b"quota",u"source_info",b"source_info",u"system_parameters",b"system_parameters",u"title",b"title",u"types",b"types",u"usage",b"usage"]) -> None: ...
