"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.api.auth_pb2
import google.api.backend_pb2
import google.api.billing_pb2
import google.api.context_pb2
import google.api.control_pb2
import google.api.documentation_pb2
import google.api.endpoint_pb2
import google.api.http_pb2
import google.api.log_pb2
import google.api.logging_pb2
import google.api.metric_pb2
import google.api.monitored_resource_pb2
import google.api.monitoring_pb2
import google.api.quota_pb2
import google.api.source_info_pb2
import google.api.system_parameter_pb2
import google.api.usage_pb2
import google.protobuf.api_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.type_pb2
import google.protobuf.wrappers_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Service(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CONFIG_VERSION_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    PRODUCER_PROJECT_ID_FIELD_NUMBER: builtins.int
    APIS_FIELD_NUMBER: builtins.int
    TYPES_FIELD_NUMBER: builtins.int
    ENUMS_FIELD_NUMBER: builtins.int
    DOCUMENTATION_FIELD_NUMBER: builtins.int
    BACKEND_FIELD_NUMBER: builtins.int
    HTTP_FIELD_NUMBER: builtins.int
    QUOTA_FIELD_NUMBER: builtins.int
    AUTHENTICATION_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    USAGE_FIELD_NUMBER: builtins.int
    ENDPOINTS_FIELD_NUMBER: builtins.int
    CONTROL_FIELD_NUMBER: builtins.int
    LOGS_FIELD_NUMBER: builtins.int
    METRICS_FIELD_NUMBER: builtins.int
    MONITORED_RESOURCES_FIELD_NUMBER: builtins.int
    BILLING_FIELD_NUMBER: builtins.int
    LOGGING_FIELD_NUMBER: builtins.int
    MONITORING_FIELD_NUMBER: builtins.int
    SYSTEM_PARAMETERS_FIELD_NUMBER: builtins.int
    SOURCE_INFO_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    id: typing.Text = ...
    title: typing.Text = ...
    producer_project_id: typing.Text = ...
    @property
    def config_version(self) -> google.protobuf.wrappers_pb2.UInt32Value: ...
    @property
    def apis(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        google.protobuf.api_pb2.Api
    ]: ...
    @property
    def types(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        google.protobuf.type_pb2.Type
    ]: ...
    @property
    def enums(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        google.protobuf.type_pb2.Enum
    ]: ...
    @property
    def documentation(self) -> google.api.documentation_pb2.Documentation: ...
    @property
    def backend(self) -> google.api.backend_pb2.Backend: ...
    @property
    def http(self) -> google.api.http_pb2.Http: ...
    @property
    def quota(self) -> google.api.quota_pb2.Quota: ...
    @property
    def authentication(self) -> google.api.auth_pb2.Authentication: ...
    @property
    def context(self) -> google.api.context_pb2.Context: ...
    @property
    def usage(self) -> google.api.usage_pb2.Usage: ...
    @property
    def endpoints(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        google.api.endpoint_pb2.Endpoint
    ]: ...
    @property
    def control(self) -> google.api.control_pb2.Control: ...
    @property
    def logs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        google.api.log_pb2.LogDescriptor
    ]: ...
    @property
    def metrics(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        google.api.metric_pb2.MetricDescriptor
    ]: ...
    @property
    def monitored_resources(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        google.api.monitored_resource_pb2.MonitoredResourceDescriptor
    ]: ...
    @property
    def billing(self) -> google.api.billing_pb2.Billing: ...
    @property
    def logging(self) -> google.api.logging_pb2.Logging: ...
    @property
    def monitoring(self) -> google.api.monitoring_pb2.Monitoring: ...
    @property
    def system_parameters(self) -> google.api.system_parameter_pb2.SystemParameters: ...
    @property
    def source_info(self) -> google.api.source_info_pb2.SourceInfo: ...
    def __init__(
        self,
        *,
        config_version: typing.Optional[google.protobuf.wrappers_pb2.UInt32Value] = ...,
        name: typing.Text = ...,
        id: typing.Text = ...,
        title: typing.Text = ...,
        producer_project_id: typing.Text = ...,
        apis: typing.Optional[typing.Iterable[google.protobuf.api_pb2.Api]] = ...,
        types: typing.Optional[typing.Iterable[google.protobuf.type_pb2.Type]] = ...,
        enums: typing.Optional[typing.Iterable[google.protobuf.type_pb2.Enum]] = ...,
        documentation: typing.Optional[
            google.api.documentation_pb2.Documentation
        ] = ...,
        backend: typing.Optional[google.api.backend_pb2.Backend] = ...,
        http: typing.Optional[google.api.http_pb2.Http] = ...,
        quota: typing.Optional[google.api.quota_pb2.Quota] = ...,
        authentication: typing.Optional[google.api.auth_pb2.Authentication] = ...,
        context: typing.Optional[google.api.context_pb2.Context] = ...,
        usage: typing.Optional[google.api.usage_pb2.Usage] = ...,
        endpoints: typing.Optional[
            typing.Iterable[google.api.endpoint_pb2.Endpoint]
        ] = ...,
        control: typing.Optional[google.api.control_pb2.Control] = ...,
        logs: typing.Optional[typing.Iterable[google.api.log_pb2.LogDescriptor]] = ...,
        metrics: typing.Optional[
            typing.Iterable[google.api.metric_pb2.MetricDescriptor]
        ] = ...,
        monitored_resources: typing.Optional[
            typing.Iterable[
                google.api.monitored_resource_pb2.MonitoredResourceDescriptor
            ]
        ] = ...,
        billing: typing.Optional[google.api.billing_pb2.Billing] = ...,
        logging: typing.Optional[google.api.logging_pb2.Logging] = ...,
        monitoring: typing.Optional[google.api.monitoring_pb2.Monitoring] = ...,
        system_parameters: typing.Optional[
            google.api.system_parameter_pb2.SystemParameters
        ] = ...,
        source_info: typing.Optional[google.api.source_info_pb2.SourceInfo] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "authentication",
            b"authentication",
            "backend",
            b"backend",
            "billing",
            b"billing",
            "config_version",
            b"config_version",
            "context",
            b"context",
            "control",
            b"control",
            "documentation",
            b"documentation",
            "http",
            b"http",
            "logging",
            b"logging",
            "monitoring",
            b"monitoring",
            "quota",
            b"quota",
            "source_info",
            b"source_info",
            "system_parameters",
            b"system_parameters",
            "usage",
            b"usage",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "apis",
            b"apis",
            "authentication",
            b"authentication",
            "backend",
            b"backend",
            "billing",
            b"billing",
            "config_version",
            b"config_version",
            "context",
            b"context",
            "control",
            b"control",
            "documentation",
            b"documentation",
            "endpoints",
            b"endpoints",
            "enums",
            b"enums",
            "http",
            b"http",
            "id",
            b"id",
            "logging",
            b"logging",
            "logs",
            b"logs",
            "metrics",
            b"metrics",
            "monitored_resources",
            b"monitored_resources",
            "monitoring",
            b"monitoring",
            "name",
            b"name",
            "producer_project_id",
            b"producer_project_id",
            "quota",
            b"quota",
            "source_info",
            b"source_info",
            "system_parameters",
            b"system_parameters",
            "title",
            b"title",
            "types",
            b"types",
            "usage",
            b"usage",
        ],
    ) -> None: ...

global___Service = Service
