# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class SystemParameters(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def rules(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[SystemParameterRule]: ...

    def __init__(self,
        *,
        rules : typing___Optional[typing___Iterable[SystemParameterRule]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SystemParameters: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"rules"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"rules",b"rules"]) -> None: ...

class SystemParameterRule(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    selector = ... # type: typing___Text

    @property
    def parameters(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[SystemParameter]: ...

    def __init__(self,
        *,
        selector : typing___Optional[typing___Text] = None,
        parameters : typing___Optional[typing___Iterable[SystemParameter]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SystemParameterRule: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"parameters",u"selector"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"parameters",b"parameters",u"selector",b"selector"]) -> None: ...

class SystemParameter(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    http_header = ... # type: typing___Text
    url_query_parameter = ... # type: typing___Text

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        http_header : typing___Optional[typing___Text] = None,
        url_query_parameter : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SystemParameter: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"http_header",u"name",u"url_query_parameter"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"http_header",b"http_header",u"name",b"name",u"url_query_parameter",b"url_query_parameter"]) -> None: ...
