"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Usage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUIREMENTS_FIELD_NUMBER: builtins.int
    RULES_FIELD_NUMBER: builtins.int
    PRODUCER_NOTIFICATION_CHANNEL_FIELD_NUMBER: builtins.int
    requirements: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    producer_notification_channel: typing.Text = ...
    @property
    def rules(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___UsageRule
    ]: ...
    def __init__(
        self,
        *,
        requirements: typing.Optional[typing.Iterable[typing.Text]] = ...,
        rules: typing.Optional[typing.Iterable[global___UsageRule]] = ...,
        producer_notification_channel: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "producer_notification_channel",
            b"producer_notification_channel",
            "requirements",
            b"requirements",
            "rules",
            b"rules",
        ],
    ) -> None: ...

global___Usage = Usage

class UsageRule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SELECTOR_FIELD_NUMBER: builtins.int
    ALLOW_UNREGISTERED_CALLS_FIELD_NUMBER: builtins.int
    SKIP_SERVICE_CONTROL_FIELD_NUMBER: builtins.int
    selector: typing.Text = ...
    allow_unregistered_calls: builtins.bool = ...
    skip_service_control: builtins.bool = ...
    def __init__(
        self,
        *,
        selector: typing.Text = ...,
        allow_unregistered_calls: builtins.bool = ...,
        skip_service_control: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "allow_unregistered_calls",
            b"allow_unregistered_calls",
            "selector",
            b"selector",
            "skip_service_control",
            b"skip_service_control",
        ],
    ) -> None: ...

global___UsageRule = UsageRule
