# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Usage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    requirements = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    producer_notification_channel = ... # type: typing___Text

    @property
    def rules(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[UsageRule]: ...

    def __init__(self,
        *,
        requirements : typing___Optional[typing___Iterable[typing___Text]] = None,
        rules : typing___Optional[typing___Iterable[UsageRule]] = None,
        producer_notification_channel : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Usage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"producer_notification_channel",u"requirements",u"rules"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"producer_notification_channel",b"producer_notification_channel",u"requirements",b"requirements",u"rules",b"rules"]) -> None: ...

class UsageRule(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    selector = ... # type: typing___Text
    allow_unregistered_calls = ... # type: bool
    skip_service_control = ... # type: bool

    def __init__(self,
        *,
        selector : typing___Optional[typing___Text] = None,
        allow_unregistered_calls : typing___Optional[bool] = None,
        skip_service_control : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> UsageRule: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"allow_unregistered_calls",u"selector",u"skip_service_control"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"allow_unregistered_calls",b"allow_unregistered_calls",u"selector",b"selector",u"skip_service_control",b"skip_service_control"]) -> None: ...
