"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class HttpRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUEST_METHOD_FIELD_NUMBER: builtins.int
    REQUEST_URL_FIELD_NUMBER: builtins.int
    REQUEST_SIZE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    RESPONSE_SIZE_FIELD_NUMBER: builtins.int
    USER_AGENT_FIELD_NUMBER: builtins.int
    REMOTE_IP_FIELD_NUMBER: builtins.int
    SERVER_IP_FIELD_NUMBER: builtins.int
    REFERER_FIELD_NUMBER: builtins.int
    LATENCY_FIELD_NUMBER: builtins.int
    CACHE_LOOKUP_FIELD_NUMBER: builtins.int
    CACHE_HIT_FIELD_NUMBER: builtins.int
    CACHE_VALIDATED_WITH_ORIGIN_SERVER_FIELD_NUMBER: builtins.int
    CACHE_FILL_BYTES_FIELD_NUMBER: builtins.int
    PROTOCOL_FIELD_NUMBER: builtins.int
    request_method: typing.Text = ...
    request_url: typing.Text = ...
    request_size: builtins.int = ...
    status: builtins.int = ...
    response_size: builtins.int = ...
    user_agent: typing.Text = ...
    remote_ip: typing.Text = ...
    server_ip: typing.Text = ...
    referer: typing.Text = ...
    cache_lookup: builtins.bool = ...
    cache_hit: builtins.bool = ...
    cache_validated_with_origin_server: builtins.bool = ...
    cache_fill_bytes: builtins.int = ...
    protocol: typing.Text = ...
    @property
    def latency(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        request_method: typing.Text = ...,
        request_url: typing.Text = ...,
        request_size: builtins.int = ...,
        status: builtins.int = ...,
        response_size: builtins.int = ...,
        user_agent: typing.Text = ...,
        remote_ip: typing.Text = ...,
        server_ip: typing.Text = ...,
        referer: typing.Text = ...,
        latency: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        cache_lookup: builtins.bool = ...,
        cache_hit: builtins.bool = ...,
        cache_validated_with_origin_server: builtins.bool = ...,
        cache_fill_bytes: builtins.int = ...,
        protocol: typing.Text = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["latency", b"latency"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "cache_fill_bytes",
            b"cache_fill_bytes",
            "cache_hit",
            b"cache_hit",
            "cache_lookup",
            b"cache_lookup",
            "cache_validated_with_origin_server",
            b"cache_validated_with_origin_server",
            "latency",
            b"latency",
            "protocol",
            b"protocol",
            "referer",
            b"referer",
            "remote_ip",
            b"remote_ip",
            "request_method",
            b"request_method",
            "request_size",
            b"request_size",
            "request_url",
            b"request_url",
            "response_size",
            b"response_size",
            "server_ip",
            b"server_ip",
            "status",
            b"status",
            "user_agent",
            b"user_agent",
        ],
    ) -> None: ...

global___HttpRequest = HttpRequest
