# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.duration_pb2 import (
    Duration as google___protobuf___duration_pb2___Duration,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class HttpRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    request_method = ... # type: typing___Text
    request_url = ... # type: typing___Text
    request_size = ... # type: int
    status = ... # type: int
    response_size = ... # type: int
    user_agent = ... # type: typing___Text
    remote_ip = ... # type: typing___Text
    server_ip = ... # type: typing___Text
    referer = ... # type: typing___Text
    cache_lookup = ... # type: bool
    cache_hit = ... # type: bool
    cache_validated_with_origin_server = ... # type: bool
    cache_fill_bytes = ... # type: int
    protocol = ... # type: typing___Text

    @property
    def latency(self) -> google___protobuf___duration_pb2___Duration: ...

    def __init__(self,
        *,
        request_method : typing___Optional[typing___Text] = None,
        request_url : typing___Optional[typing___Text] = None,
        request_size : typing___Optional[int] = None,
        status : typing___Optional[int] = None,
        response_size : typing___Optional[int] = None,
        user_agent : typing___Optional[typing___Text] = None,
        remote_ip : typing___Optional[typing___Text] = None,
        server_ip : typing___Optional[typing___Text] = None,
        referer : typing___Optional[typing___Text] = None,
        latency : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
        cache_lookup : typing___Optional[bool] = None,
        cache_hit : typing___Optional[bool] = None,
        cache_validated_with_origin_server : typing___Optional[bool] = None,
        cache_fill_bytes : typing___Optional[int] = None,
        protocol : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> HttpRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"latency"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"cache_fill_bytes",u"cache_hit",u"cache_lookup",u"cache_validated_with_origin_server",u"latency",u"protocol",u"referer",u"remote_ip",u"request_method",u"request_size",u"request_url",u"response_size",u"server_ip",u"status",u"user_agent"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"latency",b"latency"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"cache_fill_bytes",b"cache_fill_bytes",u"cache_hit",b"cache_hit",u"cache_lookup",b"cache_lookup",u"cache_validated_with_origin_server",b"cache_validated_with_origin_server",u"latency",b"latency",u"protocol",b"protocol",u"referer",b"referer",u"remote_ip",b"remote_ip",u"request_method",b"request_method",u"request_size",b"request_size",u"request_url",b"request_url",u"response_size",b"response_size",u"server_ip",b"server_ip",u"status",b"status",u"user_agent",b"user_agent"]) -> None: ...
