# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

CalendarPeriodValue = typing___NewType("CalendarPeriodValue", builtin___int)
type___CalendarPeriodValue = CalendarPeriodValue
CalendarPeriod: _CalendarPeriod

class _CalendarPeriod(
    google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[
        CalendarPeriodValue
    ]
):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    CALENDAR_PERIOD_UNSPECIFIED = typing___cast(CalendarPeriodValue, 0)
    DAY = typing___cast(CalendarPeriodValue, 1)
    WEEK = typing___cast(CalendarPeriodValue, 2)
    FORTNIGHT = typing___cast(CalendarPeriodValue, 3)
    MONTH = typing___cast(CalendarPeriodValue, 4)
    QUARTER = typing___cast(CalendarPeriodValue, 5)
    HALF = typing___cast(CalendarPeriodValue, 6)
    YEAR = typing___cast(CalendarPeriodValue, 7)

CALENDAR_PERIOD_UNSPECIFIED = typing___cast(CalendarPeriodValue, 0)
DAY = typing___cast(CalendarPeriodValue, 1)
WEEK = typing___cast(CalendarPeriodValue, 2)
FORTNIGHT = typing___cast(CalendarPeriodValue, 3)
MONTH = typing___cast(CalendarPeriodValue, 4)
QUARTER = typing___cast(CalendarPeriodValue, 5)
HALF = typing___cast(CalendarPeriodValue, 6)
YEAR = typing___cast(CalendarPeriodValue, 7)
type___CalendarPeriod = CalendarPeriod
