"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Color(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RED_FIELD_NUMBER: builtins.int
    GREEN_FIELD_NUMBER: builtins.int
    BLUE_FIELD_NUMBER: builtins.int
    ALPHA_FIELD_NUMBER: builtins.int
    red: builtins.float = ...
    green: builtins.float = ...
    blue: builtins.float = ...
    @property
    def alpha(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        red: builtins.float = ...,
        green: builtins.float = ...,
        blue: builtins.float = ...,
        alpha: typing.Optional[google.protobuf.wrappers_pb2.FloatValue] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["alpha", b"alpha"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "alpha", b"alpha", "blue", b"blue", "green", b"green", "red", b"red"
        ],
    ) -> None: ...

global___Color = Color
