"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class DateTime(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    YEAR_FIELD_NUMBER: builtins.int
    MONTH_FIELD_NUMBER: builtins.int
    DAY_FIELD_NUMBER: builtins.int
    HOURS_FIELD_NUMBER: builtins.int
    MINUTES_FIELD_NUMBER: builtins.int
    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    UTC_OFFSET_FIELD_NUMBER: builtins.int
    TIME_ZONE_FIELD_NUMBER: builtins.int
    year: builtins.int = ...
    month: builtins.int = ...
    day: builtins.int = ...
    hours: builtins.int = ...
    minutes: builtins.int = ...
    seconds: builtins.int = ...
    nanos: builtins.int = ...
    @property
    def utc_offset(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def time_zone(self) -> global___TimeZone: ...
    def __init__(
        self,
        *,
        year: builtins.int = ...,
        month: builtins.int = ...,
        day: builtins.int = ...,
        hours: builtins.int = ...,
        minutes: builtins.int = ...,
        seconds: builtins.int = ...,
        nanos: builtins.int = ...,
        utc_offset: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        time_zone: typing.Optional[global___TimeZone] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "time_offset",
            b"time_offset",
            "time_zone",
            b"time_zone",
            "utc_offset",
            b"utc_offset",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "day",
            b"day",
            "hours",
            b"hours",
            "minutes",
            b"minutes",
            "month",
            b"month",
            "nanos",
            b"nanos",
            "seconds",
            b"seconds",
            "time_offset",
            b"time_offset",
            "time_zone",
            b"time_zone",
            "utc_offset",
            b"utc_offset",
            "year",
            b"year",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions.Literal["time_offset", b"time_offset"]
    ) -> typing_extensions.Literal["utc_offset", "time_zone"]: ...

global___DateTime = DateTime

class TimeZone(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    version: typing.Text = ...
    def __init__(
        self,
        *,
        id: typing.Text = ...,
        version: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["id", b"id", "version", b"version"]
    ) -> None: ...

global___TimeZone = TimeZone
