# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

DayOfWeekValue = typing___NewType("DayOfWeekValue", builtin___int)
type___DayOfWeekValue = DayOfWeekValue
DayOfWeek: _DayOfWeek

class _DayOfWeek(
    google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[DayOfWeekValue]
):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    DAY_OF_WEEK_UNSPECIFIED = typing___cast(DayOfWeekValue, 0)
    MONDAY = typing___cast(DayOfWeekValue, 1)
    TUESDAY = typing___cast(DayOfWeekValue, 2)
    WEDNESDAY = typing___cast(DayOfWeekValue, 3)
    THURSDAY = typing___cast(DayOfWeekValue, 4)
    FRIDAY = typing___cast(DayOfWeekValue, 5)
    SATURDAY = typing___cast(DayOfWeekValue, 6)
    SUNDAY = typing___cast(DayOfWeekValue, 7)

DAY_OF_WEEK_UNSPECIFIED = typing___cast(DayOfWeekValue, 0)
MONDAY = typing___cast(DayOfWeekValue, 1)
TUESDAY = typing___cast(DayOfWeekValue, 2)
WEDNESDAY = typing___cast(DayOfWeekValue, 3)
THURSDAY = typing___cast(DayOfWeekValue, 4)
FRIDAY = typing___cast(DayOfWeekValue, 5)
SATURDAY = typing___cast(DayOfWeekValue, 6)
SUNDAY = typing___cast(DayOfWeekValue, 7)
type___DayOfWeek = DayOfWeek
