"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___DayOfWeek = DayOfWeek

class _DayOfWeek(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DayOfWeek.V],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    DAY_OF_WEEK_UNSPECIFIED = DayOfWeek.V(0)
    MONDAY = DayOfWeek.V(1)
    TUESDAY = DayOfWeek.V(2)
    WEDNESDAY = DayOfWeek.V(3)
    THURSDAY = DayOfWeek.V(4)
    FRIDAY = DayOfWeek.V(5)
    SATURDAY = DayOfWeek.V(6)
    SUNDAY = DayOfWeek.V(7)

class DayOfWeek(metaclass=_DayOfWeek):
    V = typing.NewType("V", builtins.int)

DAY_OF_WEEK_UNSPECIFIED = DayOfWeek.V(0)
MONDAY = DayOfWeek.V(1)
TUESDAY = DayOfWeek.V(2)
WEDNESDAY = DayOfWeek.V(3)
THURSDAY = DayOfWeek.V(4)
FRIDAY = DayOfWeek.V(5)
SATURDAY = DayOfWeek.V(6)
SUNDAY = DayOfWeek.V(7)
