"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Expr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    EXPRESSION_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    expression: typing.Text = ...
    title: typing.Text = ...
    description: typing.Text = ...
    location: typing.Text = ...
    def __init__(
        self,
        *,
        expression: typing.Text = ...,
        title: typing.Text = ...,
        description: typing.Text = ...,
        location: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "description",
            b"description",
            "expression",
            b"expression",
            "location",
            b"location",
            "title",
            b"title",
        ],
    ) -> None: ...

global___Expr = Expr
