# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import NewType as typing___NewType, cast as typing___cast

from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)
from google.protobuf.message import Message as google___protobuf___message___Message

builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

MonthValue = typing___NewType("MonthValue", builtin___int)
type___MonthValue = MonthValue
Month: _Month

class _Month(
    google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[MonthValue]
):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    MONTH_UNSPECIFIED = typing___cast(MonthValue, 0)
    JANUARY = typing___cast(MonthValue, 1)
    FEBRUARY = typing___cast(MonthValue, 2)
    MARCH = typing___cast(MonthValue, 3)
    APRIL = typing___cast(MonthValue, 4)
    MAY = typing___cast(MonthValue, 5)
    JUNE = typing___cast(MonthValue, 6)
    JULY = typing___cast(MonthValue, 7)
    AUGUST = typing___cast(MonthValue, 8)
    SEPTEMBER = typing___cast(MonthValue, 9)
    OCTOBER = typing___cast(MonthValue, 10)
    NOVEMBER = typing___cast(MonthValue, 11)
    DECEMBER = typing___cast(MonthValue, 12)

MONTH_UNSPECIFIED = typing___cast(MonthValue, 0)
JANUARY = typing___cast(MonthValue, 1)
FEBRUARY = typing___cast(MonthValue, 2)
MARCH = typing___cast(MonthValue, 3)
APRIL = typing___cast(MonthValue, 4)
MAY = typing___cast(MonthValue, 5)
JUNE = typing___cast(MonthValue, 6)
JULY = typing___cast(MonthValue, 7)
AUGUST = typing___cast(MonthValue, 8)
SEPTEMBER = typing___cast(MonthValue, 9)
OCTOBER = typing___cast(MonthValue, 10)
NOVEMBER = typing___cast(MonthValue, 11)
DECEMBER = typing___cast(MonthValue, 12)
type___Month = Month
