# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class PostalAddress(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    revision = ... # type: int
    region_code = ... # type: typing___Text
    language_code = ... # type: typing___Text
    postal_code = ... # type: typing___Text
    sorting_code = ... # type: typing___Text
    administrative_area = ... # type: typing___Text
    locality = ... # type: typing___Text
    sublocality = ... # type: typing___Text
    address_lines = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    recipients = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    organization = ... # type: typing___Text

    def __init__(self,
        *,
        revision : typing___Optional[int] = None,
        region_code : typing___Optional[typing___Text] = None,
        language_code : typing___Optional[typing___Text] = None,
        postal_code : typing___Optional[typing___Text] = None,
        sorting_code : typing___Optional[typing___Text] = None,
        administrative_area : typing___Optional[typing___Text] = None,
        locality : typing___Optional[typing___Text] = None,
        sublocality : typing___Optional[typing___Text] = None,
        address_lines : typing___Optional[typing___Iterable[typing___Text]] = None,
        recipients : typing___Optional[typing___Iterable[typing___Text]] = None,
        organization : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> PostalAddress: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"address_lines",u"administrative_area",u"language_code",u"locality",u"organization",u"postal_code",u"recipients",u"region_code",u"revision",u"sorting_code",u"sublocality"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"address_lines",b"address_lines",u"administrative_area",b"administrative_area",u"language_code",b"language_code",u"locality",b"locality",u"organization",b"organization",u"postal_code",b"postal_code",u"recipients",b"recipients",u"region_code",b"region_code",u"revision",b"revision",u"sorting_code",b"sorting_code",u"sublocality",b"sublocality"]) -> None: ...
