# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import Optional as typing___Optional

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class TimeOfDay(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    hours: builtin___int = ...
    minutes: builtin___int = ...
    seconds: builtin___int = ...
    nanos: builtin___int = ...
    def __init__(
        self,
        *,
        hours: typing___Optional[builtin___int] = None,
        minutes: typing___Optional[builtin___int] = None,
        seconds: typing___Optional[builtin___int] = None,
        nanos: typing___Optional[builtin___int] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "hours",
            b"hours",
            "minutes",
            b"minutes",
            "nanos",
            b"nanos",
            "seconds",
            b"seconds",
        ],
    ) -> None: ...

type___TimeOfDay = TimeOfDay
