"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TimeOfDay(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HOURS_FIELD_NUMBER: builtins.int
    MINUTES_FIELD_NUMBER: builtins.int
    SECONDS_FIELD_NUMBER: builtins.int
    NANOS_FIELD_NUMBER: builtins.int
    hours: builtins.int = ...
    minutes: builtins.int = ...
    seconds: builtins.int = ...
    nanos: builtins.int = ...
    def __init__(
        self,
        *,
        hours: builtins.int = ...,
        minutes: builtins.int = ...,
        seconds: builtins.int = ...,
        nanos: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "hours",
            b"hours",
            "minutes",
            b"minutes",
            "nanos",
            b"nanos",
            "seconds",
            b"seconds",
        ],
    ) -> None: ...

global___TimeOfDay = TimeOfDay
